name       : blobby2
version    : 1.0
release    : 5
source     :
    - https://sourceforge.net/projects/blobby/files/Blobby%20Volley%202%20%28Linux%29/1.0/blobby2-linux-1.0.tar.gz/download : ba7a049e298aaa2014c1e1ac1faf3b0256b4c66266cd4db06e7939e8695bf5e2
license    : GPL-2.0-only
component  : games.arcade
summary    : Blobby Volley is a simple arcade game with two blobs of goo.
description: |
    In Blobby Volley 2 you can play beach volleyball against friends via LAN or computer enemies with variable strength.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(sdl2)
    - libboost-devel
    - physfs-devel
setup      : |
    %patch -Np2 -i $pkgfiles/ostream-include.patch
    sed -i "s|data|/usr/share/blobby|g" src/main.cpp
    sed -i "s|file\(filename\)|file(\"/usr/share/blobby\" + filename|g" src/main.cpp
    %cmake -DCMAKE_INSTALL_PREFIX=/usr .
build      : |
    %make
install    : |
    %make_install
    install -Dm644 data/Icon.bmp $installdir/usr/share/blobby/Icon.bmp
    install -Dm644 $pkgfiles/blobby2.desktop $installdir/usr/share/applications/blobby2.desktop
    install -Dm644 $pkgfiles/blobby2.png $installdir/usr/share/pixmaps/blobby2.png
